project:
  type: website
  output-dir: docs

website:
  title: "Sundeep Rodricks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Hobbies.qmd
      - 193DS-HW-05.qmd

format:
  html:
    theme:
      mystyles.scss
    mainfont: Quicksand
    toc: true
    page-layout: full

editor: visual

